name: flutter_contacts
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  brasil_fields: ^1.14.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  gallery_saver_updated: ^3.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.1.14
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/launcher/
    - assets/icons/social/
    - assets/img/
